### ISSUE TITLE
Issue with EventLogger and loading config from the container

### ISSUE THREAD

**Issue by AlastairDewar** [DirectoryTree/LdapRecord-Lumen#3]
Hey,

I'm seeing an issue where you get the following error message
`Target class [config] does not exist.`
when carrying out the following eloquent query
`Staff::where(['samaccountname' => $request->username])->firstOrFail();.`

```
.vendor/illuminate/container/Container.php#L830
.vendor/illuminate/container/Container.php#L712
.vendor/illuminate/container/Container.php#L651
.vendor/laravel/lumen-framework/src/Application.php#L300
.vendor/illuminate/container/Container.php#L1354
.vendor/illuminate/log/LogManager.php#L453
.vendor/illuminate/log/LogManager.php#L98
.vendor/illuminate/log/LogManager.php#L595
.vendor/directorytree/ldaprecord/src/Log/EventLogger.php#L71
.vendor/directorytree/ldaprecord/src/Log/EventLogger.php#L39
.vendor/directorytree/ldaprecord/src/Log/HasLogger.php#L65
```

Following the stack-trace, it looks like this comes from the Logger which I can see has been been recently removed from the parent package.

```
        "php": ">=7.4",
        "directorytree/ldaprecord-lumen": "^1.0",
        "laravel/lumen-framework": "^8.0",
```

I've tried explicitly requiring the latest version (^2.1.2) of the base package in my composer.json, but it appears incompatible with this package.

Do you have any suggestions on how to remedy this, or if my interpretation of the removal of the EventLogger is correct?

Thanks for your help,
Ally

**Comment by stevebauman** [comment]
Hi @AlastairDewar,

I've just released [v2.0](https://github.com/DirectoryTree/LdapRecord-Lumen/releases/tag/v2.0.0) that should resolve your issues that you're experiencing.

Can you give it a shot and let me know your results?

**Comment by AlastairDewar** [comment]
Thanks @stevebauman.

It looks like it's still occurring, but now in newer `./src/Events/Logger.php`.

```
./vendor/directorytree/ldaprecord/src/Events/Logger.php:74
./vendor/directorytree/ldaprecord/src/Events/Logger.php:42
./vendor/directorytree/ldaprecord/src/Container.php:235
./vendor/directorytree/ldaprecord/src/Events/Dispatcher.php:266
./vendor/directorytree/ldaprecord/src/Events/Dispatcher.php:112
./vendor/directorytree/ldaprecord/src/Events/Dispatcher.php:93
./vendor/directorytree/ldaprecord/src/Auth/Guard.php:216
./vendor/directorytree/ldaprecord/src/Auth/Guard.php:101
./vendor/directorytree/ldaprecord/src/Auth/Guard.php:134
```

I've managed to get around the issue just now by setting the env variable LDAP_LOGGING to false.

This is not an issue for me, as the logging is not something I require and was using just for debugging.

Thanks for your help,
Ally

**Comment by stevebauman** [comment]
Happy to help @AlastairDewar!

That's strange that you're still encountering it though. Would you mind letting me know your Lumen version so I can try and debug this?

It looks like your Lumen application doesn't have the `config` singleton registered in its container. I'm not sure if that's something that was added in a later version of Lumen or not.

**Comment by stevebauman** [comment]
I've tested this again via the following:

1. Created a completely fresh Lumen 8.0 instance
2. Followed the [documentation guide](https://ldaprecord.com/docs/laravel/v2/lumen/) step-by-step
3. Enabled LDAP logging
4. Attempted querying an LDAP directory

Everything is working fine -- no errors or exceptions. All operations are also being successfully sent to the log file.

Let me know your version and I can help you debug this 😄

**Comment by stevebauman** [comment]
Closing due to inactivity.
